services:
  db:
    image: postgres:18.1-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-korf}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-korf}
      POSTGRES_DB: ${POSTGRES_DB:-korf}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 3s
      timeout: 3s
      retries: 10
    volumes:
      - korf_db:/var/lib/postgresql/data
    networks:
      - korf_net
    ports:
      - 5432:5432

  kommander:
    build:
      context: kommander
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-korf}:${POSTGRES_PASSWORD:-korf}@db:5432/${POSTGRES_DB:-korf}?sslmode=disable
      UDP_BIND: ${UDP_BIND:-0.0.0.0:8888}
      HTTP_BIND: ${HTTP_BIND:-0.0.0.0:8080}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080/tcp"
      - "8888:8888/udp"
    networks:
      - korf_net

volumes:
  korf_db:
    external: true

networks:
  korf_net:
    external: true
